def harvard_oxford_to_lobes():

    mapper = {
                    'background' : [
                        'Background',
                        ],
                    'IFG' : [
                        'Inferior Frontal Gyrus, pars triangularis', 
                        'Inferior Frontal Gyrus, pars opercularis'
                        ],
                    'pSTS' : 
                        [
                        #'Supramarginal Gyrus, anterior division', 
                        #'Supramarginal Gyrus, posterior division',
                        'Angular Gyrus',
                        'Central Opercular Cortex',
                        'Planum Temporale',
                        'Superior Temporal Gyrus, posterior division',
                        'Middle Temporal Gyrus, posterior division',
                        'Middle Temporal Gyrus, temporooccipital part',
                        #'Inferior Temporal Gyrus, posterior division',
                        #'Inferior Temporal Gyrus, temporooccipital part',
                        'Temporal Fusiform Cortex, posterior division',
                        'Temporal Occipital Fusiform Cortex',
                        "Heschl's Gyrus (includes H1 and H2)"
                        ],
                    'frontal_lobe' : [
                        'Frontal Pole',
                        'Insular Cortex',
                        'Superior Frontal Gyrus',
                        'Middle Frontal Gyrus',
                        'Inferior Frontal Gyrus, pars triangularis',
                        'Inferior Frontal Gyrus, pars opercularis',
                        'Precentral Gyrus',
                        'Frontal Operculum Cortex',
                        'Frontal Orbital Cortex',
                        'Frontal Medial Cortex',
                        'Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)',
                        ],
                    'motor_areas' : [
                                    'Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)',
                                    'Precentral Gyrus',
                                    ],
                    'temporal_lobe' : [
                        'Temporal Pole',
                        'Superior Temporal Gyrus, anterior division',
                        'Middle Temporal Gyrus, anterior division',
                        'Inferior Temporal Gyrus, anterior division',
                        'Temporal Fusiform Cortex, anterior division',
                        'Planum Polare',
                        'Superior Temporal Gyrus, posterior division',
                        'Middle Temporal Gyrus, posterior division',
                        'Middle Temporal Gyrus, temporooccipital part',
                        'Inferior Temporal Gyrus, posterior division',
                        'Inferior Temporal Gyrus, temporooccipital part',
                        'Temporal Fusiform Cortex, posterior division',
                        'Temporal Occipital Fusiform Cortex',
                        "Heschl's Gyrus (includes H1 and H2)",
                        ],
                    'anterior_temporal_lobe' : [
                        'Temporal Pole',
                        'Superior Temporal Gyrus, anterior division',
                        'Middle Temporal Gyrus, anterior division',
                        'Inferior Temporal Gyrus, anterior division',
                        'Temporal Fusiform Cortex, anterior division',
                        'Superior Temporal Gyrus, posterior division',
                        'Middle Temporal Gyrus, posterior division',
                        'Inferior Temporal Gyrus, posterior division',
                        'Temporal Fusiform Cortex, posterior division',
                        'Planum Polare',
                        'Parahippocampal Gyrus, anterior division',
                        ],
                    'parietal_lobe' : [
                        'Postcentral Gyrus',
                        'Superior Parietal Lobule',
                        'Parietal Operculum Cortex',
                        'Supramarginal Gyrus, anterior division',
                        'Supramarginal Gyrus, posterior division',
                        'Angular Gyrus',
                        'Precuneous Cortex',
                        'Central Opercular Cortex',
                        ],
                    'occipital_lobe' : [
                        'Occipital Pole',
                        'Occipital Fusiform Gyrus',
                        'Lateral Occipital Cortex, superior division',
                        'Lateral Occipital Cortex, inferior division',
                        'Intracalcarine Cortex',
                        'Cuneal Cortex',
                        'Lingual Gyrus',
                        'Planum Temporale',
                        'Supracalcarine Cortex',
                        ],
                    'limbic_system' : [
                        'Subcallosal Cortex',
                        'Parahippocampal Gyrus, anterior division',
                        'Parahippocampal Gyrus, posterior division',
                        'Paracingulate Gyrus',
                        'Cingulate Gyrus, anterior division',
                        'Cingulate Gyrus, posterior division',
                        ],
                    }
    return mapper
